### ISSUE TITLE
AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by gopinath6** [vincentcox/StaCoAn#13]
Thanks old issue fixed.any though below 2 error?

367 INFO: checking Analysis
367 INFO: Building Analysis because out00-Analysis.toc is non existent
367 INFO: Initializing module dependency graph...
373 INFO: Initializing module graph hooks...
377 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\pkgutil.                                                                                                                                                 py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\pkgutil.                                                                                                                                                 py", line 146, in _iter_file_finder_modules
    import inspect
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\inspect.                                                                                                                                                 py", line 41, in <module>
    import linecache
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\linecach                                                                                                                                                 e.py", line 11, in <module>
    import tokenize
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\tokenize                                                                                                                                                 .py", line 33, in <module>
    import re
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\re.py",                                                                                                                                                  line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

12236 INFO: Loading module hook "hook-encodings.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 13, in walk_packages
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\pkgutil.py", line 127, in iter_modules
    for name, ispkg in iter_importer_modules(i, prefix):
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\pkgutil.py", line 146, in _iter_file_finder_modules
    import inspect
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\inspect.py", line 41, in <module>
    import linecache
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\linecache.py", line 11, in <module>
    import tokenize
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\tokenize.py", line 33, in <module>
    import re
  File "c:\users\kandasam\appdata\local\programs\python\python36-32\lib\re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):

**Comment by vincentcox** [comment]
If possible, can you provide the APK? If I am correct, the program crashes at a zip inside the APK.

Thanks for taking time to report this.

**Comment by vincentcox** [comment]
Can you try `unset PYTHONPATH`? 

If that doesn't work, you can try `pip3 uninstall enum34`. (https://stackoverflow.com/questions/43124775/why-python-3-6-1-throws-attributeerror-module-enum-has-no-attribute-intflag)

**Comment by gopinath6** [comment]
Thanks it solved, 

8623 INFO: Updating manifest in C:\Users\kandasam\AppData\Roaming\pyinstaller\bincache00_py36_32bit\_sqlite3.pyd
18624 INFO: Updating resource type 24 name 2 language 1033
18731 INFO: Updating manifest in C:\Users\kandasam\AppData\Roaming\pyinstaller\bincache00_py36_32bit\sqlite3.dll
18732 INFO: Updating resource type 24 name 2 language 1033
21201 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
21207 INFO: Bootloader c:\users\kandasam\appdata\local\programs\python\python36-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
21207 INFO: checking EXE
21207 INFO: Building EXE because out00-EXE.toc is non existent
21207 INFO: Building EXE from out00-EXE.toc
21213 INFO: SRCPATH [('icon.ico', None)]
21213 INFO: Updating icons from ['icon.ico'] to C:\Users\kandasam\AppData\Local\Temp\tmpd7_w_l3y
21311 INFO: Writing RT_GROUP_ICON 0 resource with 90 bytes
21311 INFO: Writing RT_ICON 1 resource with 17778 bytes
21311 INFO: Writing RT_ICON 2 resource with 67624 bytes
21311 INFO: Writing RT_ICON 3 resource with 16936 bytes
21311 INFO: Writing RT_ICON 4 resource with 9640 bytes
21311 INFO: Writing RT_ICON 5 resource with 4264 bytes
21311 INFO: Writing RT_ICON 6 resource with 1128 bytes
21410 INFO: Appending archive to EXE C:\Users\kandasam\Dropbox\bug\Tools\MOBILE ANALYSIS\StaCoAn-master\StaCoAn-master\dist\stacoan.exe
21428 INFO: Building EXE from out00-EXE.toc completed successfully.

When i double  click the stacoan,exe  from above location, prompt is opening  and closing. 

OS: Windows 7

**Comment by vincentcox** [comment]
This is because no input file is given. If you drag and drop an APK file to it, you will see that it will start working. 

I will make an improvement that keeps the console open for a few seconds. Thanks for your input and testing!
