### ISSUE TITLE
ERROR: Unknown error: 'test-apk_apk' on Mac executable

### ISSUE THREAD

**Issue by vincentcox** [vincentcox/StaCoAn#46]
When running the Mac release, the following output is shown:
```
[INFO] jadx return code: 0
[INFO] Decompiling done.
[INFO] Searching trough files
[INFO] Searching done.
[INFO] start generating report
[ERROR] ERROR: Unknown error: 'test-apk_apk'.
```

ToDo: Disable try catch wrapper on main function to find the root cause. Maybe make a `--debug` option to disable this try catch wrapper.

**Comment by vincentcox** [comment]
More output:

```
Traceback (most recent call last):
 File "/Users/vincentcox/Downloads/StaCoAn-0.55/src/stacoan.py", line 254, in <module>
   program(parse_args())
 File "/Users/vincentcox/Downloads/StaCoAn-0.55/src/stacoan.py", line 181, in program
   overview_html.tree_view(Project.projects[project_path], file)
 File "/Users/vincentcox/Downloads/StaCoAn-0.55/src/report_html.py", line 665, in tree_view
   project)
 File "/Users/vincentcox/Downloads/StaCoAn-0.55/src/report_html.py", line 92, in get_source_code_from_file
   if file_path in Project.projects[project.name].db_files:
KeyError: 'test-apk_apk'
[7035] Failed to execute script stacoan
```

**Comment by Kevin-De-Koninck** [comment]
Issue not seen anymore, this can be closed.
